import Aside from '@/components/layout/aside/aside';
import Footer from '@/components/layout/footer/footer';
import Header from '@/components/layout/header/header';
import Wrapper from '@/components/layout/wrapper/wrapper';
import Preloader from '@/components/preloader/preloader';
import Providers from '@/components/utility/providers/providers';
import '@/styles/index.scss';
import type { Metadata } from 'next';

// $======================== RootLayout ========================$ //

export const metadata: Metadata = {
  title: "Alex Kis Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Preloader />
          <Wrapper>
            <Header />
            <Aside />
            {children}
            <Footer />
          </Wrapper>
        </Providers>
      </body>
    </html>
  );
}
